chore: ui amends based on feedback
nearform/osscheck pull request #111
Opened 2023-09-12 09:00 UTC by ShaunBaker

resolves #91 #92 #104 #97 #96 #93 #102 #98 #94 #100 #95 and #99

2023-09-13 13:52 UTC, jack-robson requested changes
Looking good only a couple small comments.

Tested all the issues and seem's to fix them all except #95 needs a little tweak.

2023-09-13 13:52 UTC, jack-robson commented on src/routes/home.tsx
> +                      size="xs"
I think  `<p>Sort by{' '}` should exist outside <Dropdown> to better match the intent of #95.

Same for the Show Dropdown.

2023-09-13 13:52 UTC, jack-robson commented on src/components/layout/header.tsx
Header.tsx is a bit hard to read, maybe move out the SVG to their own files should make it a bit easier.

2023-09-18 15:42 UTC, simoneb commented
@ShaunBaker can you please review @jack-robson 's feedback?

2023-09-19 12:03 UTC, jack-robson approved these changes

2023-09-20 09:03 UTC, merged